version: "3.8"

volumes:
  notification-service-db:

services:

  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: swvl-database
      PGDATA: "/data/postgres"
    volumes:
      - notification-service-db:/var/lib/postgresql/data
    ports:
      - "35432:5432"
   

  app:
    container_name: notification-service-server
    build: ./notification-service
    env_file: ./notification-service/.env
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: swvl-database
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "yarn run sequelize-migrate && yarn run dev" 


  # zookeeper:
  #   image: 'wurstmeister/zookeeper:latest'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka:
  #   image: 'wurstmeister/kafka:latest'
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper