version: "3.8"

volumes:
  notification-service-db:

services:

  postgres:
    container_name: notifications-database-server
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: swvl-database
      PGDATA: "/data/postgres"
    volumes:
      - notification-service-db:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    depends_on:
        - kafka

  gateway:
    container_name: notifications-gateway-server
    image: ahmednagyyy/notification-gateway
    depends_on:
      - zookeeper
      - kafka
      - service
    ports:
      - "8080:8080"


  service:
    container_name: notifications-service-server
    build: ./notification-service
    env_file: ./notification-service/.env
    depends_on:
      - postgres
    environment:
      KAFKA_HOST: kafka:9092
      NODE_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: swvl-database
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "yarn run sequelize-migrate && yarn run dev" 
    links: 
      - zookeeper
      - kafka



  zookeeper:
    container_name: notifications-sub-server
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: notifications-pub-server
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME= kafka
      - ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      