version: "3.8"

volumes:
  notification-service-db:

services:

  postgres:
    container_name: notifications-database-server
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: swvl-database
      PGDATA: "/data/postgres"
    volumes:
      - notification-service-db:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    depends_on:
        - kafka
    logging:
        driver: none      

  notification-service:
    container_name: notifications-service-server
    image: ahmednagyyy/notification-service
    depends_on:
      - zookeeper
      - kafka
      - user-service
    ports:
      - "8080:8080"


  user-service:
    container_name: users-service-server
    build: ./users-service
    env_file: ./users-service/.env
    depends_on:
      - postgres
    environment:
      BROKER_CLIENT_ID: notification-service
      SMS_TOPIC: sms_notification_topic
      PUSH_NOTIFICATION_TOPIC: push_notification_topic
      GROUP_NOTIFICATION_TOPIC: group_notification_topic
      SIGNLE_NOTIFICATION_TOPIC: single_notification_topic
      KAFKA_HOST: kafka:9092
      NODE_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: swvl-database
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "yarn run sequelize-migrate && yarn run dev" 




  zookeeper:
    container_name: notifications-sub-server
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: none        

  kafka:
    container_name: notifications-pub-server
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME= kafka
      - ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    logging:
      driver: none  
      