swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: notifications-controller
    description: Notifications Controller
paths:
  /api/notification/group:
    post:
      tags:
        - notifications-controller
      summary: sendGroupNotification
      operationId: sendGroupNotificationUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: notification
          description: notification
          required: true
          schema:
            $ref: '#/definitions/Notification'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NotificationResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/notification/single:
    post:
      tags:
        - notifications-controller
      summary: sendSingleNotification
      operationId: sendSingleNotificationUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: notification
          description: notification
          required: true
          schema:
            $ref: '#/definitions/Notification'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NotificationResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  NotificationResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
      message:
        type: string
      notificationBody:
        type: string
  Notification:
    type: object
    properties:
      audienceType:
        type: string
        enum:
          - SINGLE
          - GROUP
      body:
        type: string
      createdAt:
        type: string
        format: date-time
      groupId:
        type: string
      notificationType:
        type: string
        enum:
          - SMS
          - PUSH_NOTIFICATION
      title:
        type: string
      userId:
        type: string
